### ISSUE TITLE
webapp example panic: interface conversion: interface {} is nil, not appdash.SpanID

### ISSUE THREAD

**Issue by soamvasani** [sourcegraph/appdash#189]
Thanks for appdash, it looks pretty neat!

I followed the instructions to install appdash and run the example webapp:

```
$ go get -u sourcegraph.com/sourcegraph/appdash/...
$ webapp
```

Opened http://localhost:8699 in the browser, and got:

```
PANIC: interface conversion: interface {} is nil, not appdash.SpanID
goroutine 8 [running]:
github.com/codegangsta/negroni.(*Recovery).ServeHTTP.func1(0x17c3080, 0xc420168018, 0xc42013ef00)
	/Users/soam/gopath/src/github.com/codegangsta/negroni/recovery.go:41 +0x13a
panic(0x13f00e0, 0xc420166740)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
main.Home(0x164e880, 0xc42015e6a0, 0xc42017c300)
	/Users/soam/gopath/src/sourcegraph.com/sourcegraph/appdash/examples/cmd/webapp/main.go:106 +0x494
net/http.HandlerFunc.ServeHTTP(0x1494458, 0x164e880, 0xc42015e6a0, 0xc42017c300)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4200152c0, 0x164e880, 0xc42015e6a0, 0xc42017c300)
	/Users/soam/gopath/src/github.com/gorilla/mux/mux.go:114 +0x10c
github.com/codegangsta/negroni.Wrap.func1(0x164e880, 0xc42015e6a0, 0xc42000bf00, 0xc42015e6c0)
	/Users/soam/gopath/src/github.com/codegangsta/negroni/negroni.go:46 +0x4d
github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc42014c6a0, 0x164e880, 0xc42015e6a0, 0xc42000bf00, 0xc42015e6c0)
	/Users/soam/gopath/src/github.com/codegangsta/negroni/negroni.go:29 +0x4e
github.com/codegangsta/negroni.middleware.ServeHTTP(0x164ac00, 0xc42014c6a0, 0xc42014c740, 0x164e880, 0xc42015e6a0, 0xc42000bf00)
	/Users/soam/gopath/src/github.com/codegangsta/negroni/negroni.go:38 +0xb4
github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0x164e880, 0xc42015e6a0, 0xc42000bf00)
	/Users/soam/gopath/src/github.com/codegangsta/negroni/negroni.go:38 +0x60
sourcegraph.com/sourcegraph/appdash/httptrace.Middleware.func1(0x17c3080, 0xc420168018, 0xc42000bf00, 0xc42015e640)
	/Users/soam/gopath/src/sourcegraph.com/sourcegraph/appdash/httptrace/server.go:84 +0x29f
github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc42014c420, 0x17c3080, 0xc420168018, 0xc42000bf00, 0xc42015e640)
	/Users/soam/gopath/src/github.com/codegangsta/negroni/negroni.go:29 +0x4e
github.com/codegangsta/negroni.middleware.ServeHTTP(0x164ac00, 0xc42014c420, 0xc42014c720, 0x17c3080, 0xc420168018, 0xc42000bf00)
	/Users/soam/gopath/src/github.com/codegangsta/negroni/negroni.go:38 +0xb4
github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0x17c3080, 0xc420168018, 0xc42000bf00)
	/Users/soam/gopath/src/github.com/codegangsta/negroni/negroni.go:38 +0x60
github.com/codegangsta/negroni.(*Static).ServeHTTP(0xc42013f4a0, 0x17c3080, 0xc420168018, 0xc42000bf00, 0xc42015e620)
	/Users/soam/gopath/src/github.com/codegangsta/negroni/static.go:53 +0x71c
github.com/codegangsta/negroni.middleware.ServeHTTP(0x16492c0, 0xc42013f4a0, 0xc42014c700, 0x17c3080, 0xc420168018, 0xc42000bf00)
	/Users/soam/gopath/src/github.com/codegangsta/negroni/negroni.go:38 +0xb4
github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0x17c3080, 0xc420168018, 0xc42000bf00)
	/Users/soam/gopath/src/github.com/codegangsta/negroni/negroni.go:38 +0x60
github.com/codegangsta/negroni.(*Logger).ServeHTTP(0xc42013ef30, 0x17c3080, 0xc420168018, 0xc42000bf00, 0xc42015e600)
	/Users/soam/gopath/src/github.com/codegangsta/negroni/logger.go:65 +0x89
github.com/codegangsta/negroni.middleware.ServeHTTP(0x1649200, 0xc42013ef30, 0xc42014c6e0, 0x17c3080, 0xc420168018, 0xc42000bf00)
	/Users/soam/gopath/src/github.com/codegangsta/negroni/negroni.go:38 +0xb4
github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0x17c3080, 0xc420168018, 0xc42000bf00)
	/Users/soam/gopath/src/github.com/codegangsta/negroni/negroni.go:38 +0x60
github.com/codegangsta/negroni.(*Recovery).ServeHTTP(0xc42013ef00, 0x17c3080, 0xc420168018, 0xc42000bf00, 0xc42015e5e0)
	/Users/soam/gopath/src/github.com/codegangsta/negroni/recovery.go:64 +0x82
github.com/codegangsta/negroni.middleware.ServeHTTP(0x1649280, 0xc42013ef00, 0xc42014c6c0, 0x17c3080, 0xc420168018, 0xc42000bf00)
	/Users/soam/gopath/src/github.com/codegangsta/negroni/negroni.go:38 +0xb4
github.com/codegangsta/negroni.(*Negroni).ServeHTTP(0xc42013f500, 0x164e7c0, 0xc4201b80e0, 0xc42000bf00)
	/Users/soam/gopath/src/github.com/codegangsta/negroni/negroni.go:86 +0x10d
net/http.serverHandler.ServeHTTP(0xc420099130, 0x164e7c0, 0xc4201b80e0, 0xc42000bf00)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4201503c0, 0x164f040, 0xc420142f40)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
```

**Comment by peterfebin** [comment]
+1

**Comment by keegancsmith** [comment]
The offending line in question is https://github.com/sourcegraph/appdash/blob/master/examples/cmd/webapp/main.go#L106

I wonder if this has been broken since `net/context` was added to the go stdlib? Or maybe something else is just going wrong such that we don't have a span associated with the gorilla context. cc @slimsag

**Comment by adpoint** [comment]
+1

**Comment by adpoint** [comment]
why?

**Comment by keegancsmith** [comment]
Took a look into this. `gorilla/context` assumes the `*http.Request` pointer never changes. However, this is not true. Especially since we now have `WithContext` which returns a new `*http.Request`. `gorila/mux` uses `WithContext`. It seems there is an open issue about this and it won't be fixed https://github.com/gorilla/context/issues/32

So the proper fix here is to stop using `gorilla/context`. I'll send a PR for that now.
